name: whoami
description: A simple HTTP echo service for testing SwarmCLI chart delivery
version: 0.1.0
appVersion: "v1.11.0"
maintainers:
  - name: Eldara
    url: https://github.com/eldara
keywords:
  - whoami
  - test
  - traefik
